[package]
name = "ZTM"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# to include bill_manager.rs in the module tree

[dependencies]
